### ISSUE TITLE
Graph isn't showing a link

### ISSUE THREAD

**Issue by amandasage** [lotas/contentful-graph-web#2]
Hey Lotas,

I have a Contentful user who created this content type:

![image](https://user-images.githubusercontent.com/33262033/83162043-141e9380-a0be-11ea-9655-f341f0c4976e.png)

Yet the graph he generates looks like 
![image](https://user-images.githubusercontent.com/33262033/83162119-2ac4ea80-a0be-11ea-848e-e8440adc586c.png)

instead of 
![image](https://user-images.githubusercontent.com/33262033/83162144-31ebf880-a0be-11ea-86b4-802b6769c602.png)

Thank you!

**Comment by lotas** [comment]
hi @amandasage 
Thank you for reporting this. 
Would you be able to provide more details please? Ideally a json model, so I can see what types are there, and how this one-to-many relation is being set? 

Thanks

**Comment by amandasage** [comment]
Hi there,
The content type Magazine is set up as below:

{
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "jb0qfg4kf94z"
      }
    },
    "id": "magazine",
    "type": "ContentType",
    "createdAt": "2020-05-22T13:26:15.596Z",
    "updatedAt": "2020-05-22T13:26:15.596Z",
    "environment": {
      "sys": {
        "id": "master",
        "type": "Link",
        "linkType": "Environment"
      }
    },
    "revision": 1
  },
  "displayField": "name",
  "name": "Magazine",
  "description": "",
  "fields": [
    {
      "id": "id",
      "name": "ID",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "disabled": false,
      "omitted": false
    },
    {
      "id": "name",
      "name": "Name",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "disabled": false,
      "omitted": false
    },
    {
      "id": "category",
      "name": "Category",
      "type": "Symbol",
      "localized": false,
      "required": true,
      "disabled": false,
      "omitted": false
    },
    {
      "id": "issues",
      "name": "Issues",
      "type": "Array",
      "localized": false,
      "required": false,
      "disabled": false,
      "omitted": false,
      "items": {
        "type": "Link",
        "validations": [],
        "linkType": "Entry"
      }
    }
  ]
}

Let me know if you need anything else!

**Comment by lotas** [comment]
@amandasage  Thanks, that explains.
In order to determine relationship, it needs to be specified on the contentful side that "references many" field accepts entities only of the specific type. 
When you edit the field `Magazine.issues`, please check that it expects only certain type for validation:
![image](https://user-images.githubusercontent.com/83861/83294836-46c7a980-a1ee-11ea-97c4-9657434caab6.png)

Then JSON model for this field would look like
```json
 {
      "id": "issues",
      "name": "issues",
      "type": "Array",
      "localized": false,
      "required": false,
      "validations": [],
      "disabled": false,
      "omitted": false,
      "items": {
        "type": "Link",
        "validations": [
          {
            "linkContentType": [
              "issue"
            ]
          }
        ],
        "linkType": "Entry"
      }
```
which will make it possible for link to appear in the graph.
Hope that helps.
Cheers

**Comment by amandasage** [comment]
Thank you so much!!!
