### ISSUE TITLE
Update package.json to use latest contentful-graph to fix issue of lotas/contentful-graph/issues/19

### ISSUE THREAD

**Issue by Swissbite** [lotas/contentful-graph-web#3]
Please update the package.json to reflect changes issued by lotas/contentful-graph/issues/19 :-)

**Comment by lotas** [comment]
Done :) thanks!

**Comment by Swissbite** [comment]
Could you also push to the docker registry? Or who did that? :-)

**Comment by lotas** [comment]
Ah! I thought about this, but forgot to test it. Will test if it still works and push new image. Thanks! :)
