### ISSUE TITLE
contentful-graph.yaraslav.com is down

### ISSUE THREAD

**Issue by cerupcat** [lotas/contentful-graph-web#9]
I'm not sure if this is intentional or not, but the website is contentful-graph.yaraslav.com/ is not resolving.

**Comment by lotas** [comment]
@cerupcat oh, thanks! I was moving servers around, forgot to restore this one. Will check

**Comment by lotas** [comment]
Sorry, forgot to mention that it is online ;) Thanks!

**Comment by cerupcat** [comment]
Awesome, thanks!
ᐧ
